# 베이스 이미지 설정
FROM ubuntu:18.04

# nginx 설치
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install nginx

#  포트 지정
EXPOSE 80

# 웹 콘텐츠 배치 - 지금 바로 실행되지 않고 다음번째 빌드할 때 실행이 된다.
ONBUILD ADD website.tar /var/www/html

# nginx 실행
CMD ["nginx", "-g", "daemon off;"]
